name: code-push

on:
  push:
    branches:
      - 'main'
      - '**_fixes'

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - name: Init the github-actions repo
        uses: aerius/github-actions/init@v1.1

      - uses: ./aerius-github-actions/events/push-event-action
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          ROOT_POM_DIRECTORY: repo/source

      - uses: ./aerius-github-actions/extras/docker-build-or-publish-based-on-maven-project-version-action
        with:
          DOCKER_REGISTRY_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          DOCKER_IMAGE_NAME: ${{ github.event.repository.name }}
          DOCKER_WORK_DIRECTORY: repo/source
          ROOT_POM_DIRECTORY: repo/source
          DOCKER_BUILD_PLATFORMS: linux/amd64,linux/arm64
